services:
  # 1번 상자: 프로메테우스 (데이터 수집기)
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Linux Docker에서 호스트 머신 접근용

  # 2번 상자: 그라파나 (데이터 시각화/대시보드)
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3100:3000"
