name: SonarCloud Analysis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        # 깃허브 메인 화면에 running-club 폴더가 한 번 더 있는 구조라면 이 경로가 맞습니다.
        working-directory: ./running-club
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # [중요] 이미지_73e900.png 확인 결과 이름은 SONAR_TOKEN입니다.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.projectKey=hiraio_running-club \
          -Dsonar.organization=hiraio \
          -Dsonar.host.url=https://sonarcloud.io \
          -DskipTests
